  - name: check test coverage
    id: coverage
    uses: vladopajic/go-test-coverage@v2
    continue-on-error: true
    with:
      profile: cover.out
      threshold-file: 80
    ## when token is not specified (value '') this feature is turned off
    ## in this example badge is created and committed only for main branch
    git-token: ${{ github.ref_name == 'main' && secrets.GITHUB_TOKEN || '' }}
    ## name of branch where badges are stored
    ## ideally this should be orphan branch (see below how to create this branch)
    git-branch: badges 
    